# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scheduler_ui.ui'
#
# Created: Sun May 11 20:41:52 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PIL import Image

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    
    window = None 		
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(798, 641)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.ResourceListBox = QtGui.QListView(self.centralwidget)
        self.ResourceListBox.setGeometry(QtCore.QRect(310, 300, 241, 151))
        self.ResourceListBox.setObjectName(_fromUtf8("ResourceListBox"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 280, 201, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(36, 400, 241, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.AddResourceButton = QtGui.QPushButton(self.layoutWidget)
        self.AddResourceButton.setObjectName(_fromUtf8("AddResourceButton"))
        self.horizontalLayout_4.addWidget(self.AddResourceButton)
        self.DeleteResourceButton = QtGui.QPushButton(self.layoutWidget)
        self.DeleteResourceButton.setObjectName(_fromUtf8("DeleteResourceButton"))
        self.horizontalLayout_4.addWidget(self.DeleteResourceButton)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 20, 561, 201))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.TasksListBox = QtGui.QListView(self.layoutWidget1)
        self.TasksListBox.setMidLineWidth(2)
        self.TasksListBox.setObjectName(_fromUtf8("TasksListBox"))
        self.verticalLayout_2.addWidget(self.TasksListBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.DependencyListBox = QtGui.QListView(self.layoutWidget1)
        self.DependencyListBox.setObjectName(_fromUtf8("DependencyListBox"))
        self.verticalLayout_3.addWidget(self.DependencyListBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(140, 500, 591, 81))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.SaveFilesButton = QtGui.QPushButton(self.layoutWidget2)
        self.SaveFilesButton.setObjectName(_fromUtf8("SaveFilesButton"))
        self.horizontalLayout_3.addWidget(self.SaveFilesButton)
        self.LoadFilesButton = QtGui.QPushButton(self.layoutWidget2)
        self.LoadFilesButton.setObjectName(_fromUtf8("LoadFilesButton"))
        self.horizontalLayout_3.addWidget(self.LoadFilesButton)
        self.QuitButton = QtGui.QPushButton(self.layoutWidget2)
        self.QuitButton.setObjectName(_fromUtf8("QuitButton"))
        self.horizontalLayout_3.addWidget(self.QuitButton)
        self.NewTaskButton = QtGui.QPushButton(self.centralwidget)
        self.NewTaskButton.setGeometry(QtCore.QRect(50, 70, 171, 27))
        self.NewTaskButton.setObjectName(_fromUtf8("NewTaskButton"))
	QtCore.QObject.connect(self.NewTaskButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.NewTaskButtonClicked)

        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(21, 41, 157, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(31, 128, 237, 85))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.NameText = QtGui.QLineEdit(self.layoutWidget3)
        self.NameText.setObjectName(_fromUtf8("NameText"))
        self.gridLayout.addWidget(self.NameText, 0, 1, 1, 1)
        self.DurationText = QtGui.QLineEdit(self.layoutWidget3)
        self.DurationText.setObjectName(_fromUtf8("DurationText"))
        self.gridLayout.addWidget(self.DurationText, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 220, 241, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.EditButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.EditButton.setObjectName(_fromUtf8("EditButton"))
        self.horizontalLayout_5.addWidget(self.EditButton)
        self.DeleteButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.DeleteButton.setObjectName(_fromUtf8("DeleteButton"))
        self.horizontalLayout_5.addWidget(self.DeleteButton)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 300, 241, 80))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.ResourceText = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.ResourceText.setObjectName(_fromUtf8("ResourceText"))
        self.horizontalLayout_6.addWidget(self.ResourceText)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(580, 330, 121, 51))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.CreateGraphButton = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.CreateGraphButton.setObjectName(_fromUtf8("CreateGraphButton"))
        self.horizontalLayout_7.addWidget(self.CreateGraphButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "List view of resources", None, QtGui.QApplication.UnicodeUTF8))
        self.AddResourceButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteResourceButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "List View of Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Highlight Dependency for respective highlighted task", None,QtGui.QApplication.UnicodeUTF8))
        self.SaveFilesButton.setText(QtGui.QApplication.translate("MainWindow", "SAVE", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadFilesButton.setText(QtGui.QApplication.translate("MainWindow", "LOAD", None, QtGui.QApplication.UnicodeUTF8))
        self.QuitButton.setText(QtGui.QApplication.translate("MainWindow", "QUIT", None, QtGui.QApplication.UnicodeUTF8))
        self.NewTaskButton.setText(QtGui.QApplication.translate("MainWindow", "New Task", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Task information:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.EditButton.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Enter Resource", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateGraphButton.setText(QtGui.QApplication.translate("MainWindow", "Create  Graph", None, QtGui.QApplication.UnicodeUTF8))

    def addEvents(self):	
	self.NewTaskButton.clicked.connect(self.NewTaskButtonClicked)
			    		
	
    def NewTaskButtonClicked(self):
	import sys		  		
	from AddNewTask_ui import Ui_Dialog	
	Dialog = QtGui.QDialog()
    	ui1 = Ui_Dialog()
    	ui1.setupUi(Dialog)
    	Dialog.show()
		
if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)    
    MainWindow.show()
    img = Image.open("layergantt.png")
    img.show()	
    ui.addEvents()
    sys.exit(app.exec_())
